import React from 'react'

const SCard = () => {
  return (
    <div>
        Cards Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur obcaecati ducimus voluptatum deserunt accusamus? Laborum nobis accusantium veritatis aut porro vitae quibusdam quo debitis? Totam aspernatur, cum suscipit repellendus facilis deserunt qui ipsam ab quae earum asperiores velit fuga obcaecati! Placeat eveniet necessitatibus sit repellendus maxime! Distinctio autem facilis esse earum alias iure nulla nobis debitis repudiandae provident. Sed doloremque cumque eos alias, iusto, sequi perspiciatis facilis excepturi corporis repellat aliquam doloribus dolorem nisi quo ipsum quia cum. Necessitatibus corporis laboriosam odit ab sunt, harum asperiores enim. Officiis ut ducimus deserunt. Magnam laborum incidunt beatae, quas architecto aliquam debitis amet obcaecati aliquid aspernatur inventore nihil neque accusantium quae pariatur id maiores nostrum ullam dicta tempore. Ratione laborum necessitatibus quos velit exercitationem consequatur facere molestiae, id delectus, mollitia soluta error repudiandae? Eaque perspiciatis nostrum similique placeat maiores unde voluptate aperiam sint aliquid ea, nihil rem nobis quam dolore. Libero dolore quasi veritatis explicabo quod iste aperiam voluptatum ducimus saepe? Autem sit, tenetur deserunt quaerat et minus deleniti optio? Optio neque enim quos vel error doloribus cumque nulla dicta dolores, ab esse consequatur mollitia inventore cupiditate incidunt magnam sapiente harum eaque, dolorem minima vitae! Dolores in alias soluta eos libero deserunt impedit ullam voluptatibus maxime quae atque assumenda accusantium obcaecati dolor aliquid magnam dignissimos, laboriosam modi maiores accusamus! Laborum, provident fugiat autem assumenda cumque consequuntur itaque, dolore odio deleniti accusamus incidunt quos praesentium libero ipsam quia necessitatibus doloremque animi iste voluptas. Alias recusandae nostrum deserunt placeat impedit accusamus doloremque, laborum necessitatibus, quidem consequatur quas, ducimus et autem. Et repellendus est animi ullam voluptatem eum cupiditate at, ea repudiandae iste sint, distinctio vero possimus, illum consequatur esse non provident ratione corporis quasi totam laudantium. Dolore aut porro vero sunt neque fugiat quos, voluptatibus maiores assumenda consequatur ratione deserunt. Consequatur voluptatibus quasi aliquam iusto.
      
    </div>
  )
}

export default SCard
